### ISSUE TITLE
Sharphound versions past 2.4.1 not working when running in shell using runas /netonly

### ISSUE THREAD

**Issue by robertstrom** [BloodHoundAD/SharpHound#120]
I have been trying to use Sharphound to collect from a non-domain joined system (which is the way that I have always previously collected) when running from a shell launched using the `runas /netonly` command as is documented.

I am able to use this method successfully when using version 2.4.1, but that version only works with older versions of Bloodhound. Even though version 2.4.1 says that it works with version 5.0.0 release of Bloodhound the files fail to ingest into Bloodhound CE (version 2.5.7 and 2.5.8 both give the same message about Bloodhound compatibility yet those files do import into BH CE).

The error message that I get when attempting to use any Sharphound past version 2.4.1 is:

**Unable to resolve a domain to use, manually specify one or check spelling**

I have tried numerous command line iterations to try and get a current version of Sharphound to work. Examples:

```
.\SharpHound.exe --CollectionMethods All -d <domain>.ad.<domain>.local --disablecertverification --overrideusername pentest01@<domain>.ad.<domain>.local --domaincontroller <domain controller>.<domain>.ad.<domain>.local

.\SharpHound.exe -d "<domain>.ad.<domain>.local" --disablecertverification --overrideusername "<domain>\pentest01" --domaincontroller "<domain controller>.<domain>.ad.<domain>.local"

.\SharpHound.exe -d <domain>.ad.<domain>.local --disablecertverification --overrideusername pentest01@<domain>.ad.<domain>.local --domaincontroller <domain controller>.<domain>.ad.<domain>.local

.\SharpHound.exe --CollectionMethods All -d <domain>.ad.<domain>.local --overrideusername pentest01@<domain>.ad.<domain>.local --domaincontroller <IP Address>

.\SharpHound.exe --CollectionMethods All -d <domain>.ad.<domain>.local --disablecertverification --overrideusername pentest01@<domain>.ad.<domain>.local --domaincontroller <IP Address>
```

I have also tried using `--domain` insted of `-d` and that made no difference

I have validated that the authentication within the shell launched using the `runas` command is valid by using the `net view` command:

```
net view \\<Domain FQDN>\
```

When doing this I see the NETLOGON and SYSVOL shares so I know that I am authenticated to the domain. I know that DNS resolution is working. I can use `nslookup` to query for the **Domain FQDN** and get back a list of domain controllers

```
nslookup <Domain FQDN>

returns list of domain controller IP addresses
```

I am also able to use nslookup to query the domain controller used in the Sharphound commands.

The screenshot below shows the `net view` command showing successful authentication of the user against the domain by returning the domain controller shares, **NETLOGON** and **SYSVOL** (I have executed the same `net view` command on the same system in a shell the was not launched using the `runas /netonly` command and it returns **access denied**

The screenshot also shows the command run and the returned error message 

![image](https://github.com/user-attachments/assets/4230b837-7bf9-498a-b1f3-97fafb26bd28)

I have used Sharphound version 2.5.1 successfully on a domain joined machine (but it is a royal PITA because Defender EDR is running on the domain joined machine) using the same commands and it works, so there definitely appears to be an issue with seeing the domain when launched from a shell running on a machine that is not domain joined.

Given the issues with running Sharphound on a domain joined machine that has Defender EDR running on it I would much rather run Sharphound from my non-domain joined Commando VM that does not have Defender EDR running on it.

Am I doing something wrong? Am I missing something? Is there a way to get the current versions of Sharphound to work from a non-domain joined machine?

If not, please, please fix this.

Thanks!

**Comment by robertstrom** [comment]
I just reviewed the post below - ["Error in consumer" when connecting to LDAP server with SH v2.5.x](https://github.com/BloodHoundAD/SharpHound/issues/118) -  in more detail and, even though the error is not the same, the LDAP failure was similar enough it made me retry version 2.5.8 using the `--ldapusername` and `--ldappassword` arguments that it looks like it is going to work.

If I run the command without those parameters I get the same error as before:

**Unable to resolve a domain to use, manually specify one or check spelling**

When I run the command using the two **ldap** arguments I can see Sharphound start to talk to AD. I don't want to let it rip right now since it is outside of business hours and and a weekend and I don't want to bug the on call SOC person with a high priority ticket ;-)

I will fully test on Monday and validate for sure, but it does look like v2.5.8 fixes the issue as long as you use the two **ldap** arguments for user name and password.

**Comment by robertstrom** [comment]
UPDATE: While it looks like it is working when pointed to a Server 2022 domain running at the Server 2016 Forest and Domain functional levels, it looks like there are issues when pointing it to a Server 2025 Forest / test forest running at the default forest and domain functional modes

Windows2025Forest
Windows2025Domain

Again, the Sharphound v2.4.1 works from a non-domain joined machine running from a shell launched using the `runas /netonly` but the v2.5.8 fails to work

The two screenshots below show v2.4.1 working

![image](https://github.com/user-attachments/assets/cf48542e-6fee-478c-9d22-c70f4c824bc1)

![image](https://github.com/user-attachments/assets/98745ce6-79ca-40db-a676-57b0738e55f9)

This screenshot shows v2.5.8 not working

![image](https://github.com/user-attachments/assets/e46e6863-78c0-4a31-8d40-cbb3bf6c6507)



Here is a portion of the error text. What I captured was too large to post directly. I have saved the copied error text to a text file and attached it below.

```
PS C:\users\rstrom\Desktop\SharpHound-v2.5.8> .\SharpHound.exe --CollectionMethods All -d server2025root.local --disablecertverification --overrideusername administrator@server2025root.local --ldapusername 'administrator@server2025roor.local' --ldappassword 'P@ssw0rd!' --domaincontroller dc-1.server2025root.local
2024-10-19T20:11:19.8131739-07:00|INFORMATION|This version of SharpHound is compatible with the 5.0.0 Release of BloodHound
2024-10-19T20:11:20.0880898-07:00|INFORMATION|Resolved Collection Methods: Group, LocalAdmin, GPOLocalGroup, Session, LoggedOn, Trusts, ACL, Container, RDP, ObjectProps, DCOM, SPNTargets, PSRemote, UserRights, CARegistry, DCRegistry, CertServices
2024-10-19T20:11:20.1315803-07:00|INFORMATION|Initializing SharpHound at 8:11 PM on 10/19/2024
2024-10-19T20:11:20.6048884-07:00|INFORMATION|Flags: Group, LocalAdmin, GPOLocalGroup, Session, LoggedOn, Trusts, ACL, Container, RDP, ObjectProps, DCOM, SPNTargets, PSRemote, UserRights, CARegistry, DCRegistry, CertServices
2024-10-19T20:11:20.7684429-07:00|INFORMATION|Beginning LDAP search for Server2025Root.local
2024-10-19T20:11:21.0137916-07:00|INFORMATION|Beginning LDAP search for Server2025Root.local Configuration NC
2024-10-19T20:11:21.0607445-07:00|INFORMATION|[CommonLib ACLProc]Building GUID Cache for SERVER2025ROOT.LOCAL
2024-10-19T20:11:21.0607445-07:00|INFORMATION|[CommonLib ACLProc]Building GUID Cache for SERVER2025ROOT.LOCAL
2024-10-19T20:11:21.1355600-07:00|INFORMATION|Producer has finished, closing LDAP channel
2024-10-19T20:11:21.1494893-07:00|INFORMATION|LDAP channel closed, waiting for consumers
2024-10-19T20:11:21.3286971-07:00|ERROR|error in consumer
System.DirectoryServices.AccountManagement.PrincipalServerDownException: The server could not be contacted. ---> System.DirectoryServices.Protocols.LdapException: The LDAP server is unavailable.
   at System.DirectoryServices.Protocols.LdapConnection.Connect()
   at System.DirectoryServices.Protocols.LdapConnection.SendRequestHelper(DirectoryRequest request, Int32& messageID)
   at System.DirectoryServices.Protocols.LdapConnection.SendRequest(DirectoryRequest request, TimeSpan requestTimeout)
   at System.DirectoryServices.AccountManagement.PrincipalContext.ReadServerConfig(String serverName, ServerProperties& properties)
   --- End of inner exception stack trace ---
   at System.DirectoryServices.AccountManagement.PrincipalContext.ReadServerConfig(String serverName, ServerProperties& properties)
   at System.DirectoryServices.AccountManagement.PrincipalContext.DoServerVerifyAndPropRetrieval()
   at System.DirectoryServices.AccountManagement.PrincipalContext..ctor(ContextType contextType, String name, String container, ContextOptions options, String userName, String password)
   at System.DirectoryServices.AccountManagement.PrincipalContext..ctor(ContextType contextType)
   at SharpHoundCommonLib.LdapUtils.<GetDomainNameFromSid>d__30.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at SharpHoundCommonLib.LdapUtils.<LookupSidType>d__24.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at SharpHoundCommonLib.LdapUtils.<ResolveIDAndType>d__23.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at SharpHoundCommonLib.Processors.ACLProcessor.<ProcessACL>d__14.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Threading.Tasks.Sources.ManualResetValueTaskSourceCore`1.GetResult(Int16 token)
   at Sharphound.Extensions.<ToArrayAsync>d__6`1.MoveNext() in D:\a\SharpHound\SharpHound\src\Extensions.cs:line 96
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Sharphound.Extensions.<ToArrayAsync>d__6`1.MoveNext() in D:\a\SharpHound\SharpHound\src\Extensions.cs:line 96
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Sharphound.Runtime.ObjectProcessors.<ProcessComputerObject>d__22.MoveNext() in D:\a\SharpHound\SharpHound\src\Runtime\ObjectProcessors.cs:line 190
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Sharphound.Runtime.ObjectProcessors.<ProcessObject>d__19.MoveNext() in D:\a\SharpHound\SharpHound\src\Runtime\ObjectProcessors.cs:line 69
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Sharphound.Runtime.LDAPConsumer.<ConsumeSearchResults>d__0.MoveNext() in D:\a\SharpHound\SharpHound\src\Runtime\LDAPConsumer.cs:line 37
2024-10-19T20:11:21.3321735-07:00|ERROR|error in consumer
```

I am able to run v2.5.8 successfully on the Server 2025 domain controller even with **Domain controller: LDAP server Enforce signing requirements** enabled (I had to disable this to have any success when running remotely from a non-domain joined machine)

![image](https://github.com/user-attachments/assets/b63240b3-cb76-4649-b0c5-7750de21bfa2)


![image](https://github.com/user-attachments/assets/3f4e5475-5ccf-4942-9472-c0ecfd4c47a5)

[sharphound_v2.5.8_error_server2025_domain.txt](https://github.com/user-attachments/files/17448582/sharphound_v2.5.8_error_server2025_domain.txt)

**Comment by rvazarkar** [comment]
This is really interesting information. First of all, we actually sign and seal our LDAP traffic on non-ssl. As far as I've been able to tell, enabling signing on SSL connections actually causes the connections to fail, but I'll have to retest that.

The exception on PrincipalContext is definitely a problem that I'll add a ticket to fix. If anything I would have expected 2.5.X versions to work _better_ in a netonly environment since it implements lots of extra checks and connection attempts, so this is surprising to me. The fact that the behavior changes based on functional level is also pretty strange. I'm wondering if fixing the principalcontext exceptions will allow things to continue as expected

**Comment by robertstrom** [comment]
UPDATE: Using version 2.5.8

Over the weekend I kicked off an initial test from a Windows 10 Commando VM using **runas /netonly**. I did not want the test to run to completion because I did not want to trigger a security alert. From the short test it looked like v2.5.8 was conencting to the LDAP server when using the `--ldapusername` and -`-ldappassword` arguments.

Well, it's no longer the weekend and I have kicked off the full run of Sharphound v2.5.8 from the Command VM and it looks like it is running and collecting data, but it is also throwing a LOT of errors.

Text file with error information attached.

The first run you see in the attached file shows the results when not using the `--ldapusername` and --`ldappassword` arguments.

The second run when using the arguments does appear to be collecting data. You can see lines like the lines below splattered in with all the error messages:

2024-10-21T08:30:15.1781189-07:00|INFORMATION|Status: 321 objects finished (+321 10.7)/s -- Using 100 MB RAM
2024-10-21T08:30:50.8818714-07:00|INFORMATION|Status: 927 objects finished (+465 14.26154)/s -- Using 150 MB RAM

2024-10-21T08:42:47.4984970-07:00|INFORMATION|Status: 32199 objects finished (+3396 41.17519)/s -- Using 147 MB RAM
2024-10-21T08:43:17.5169286-07:00|INFORMATION|Status: 32301 objects finished (+3498 39.77956)/s -- Using 147 MB RAM

I'm going to let it run until it finishes and see what I end up with.

[sharphound_v2.5.8_error_in_consumer.txt](https://github.com/user-attachments/files/17463695/sharphound_v2.5.8_error_in_consumer.txt)

**Comment by rvazarkar** [comment]
Yeah the errors all generally appear to be related to the same thing: .net is throwing exceptions on the `using` statement (which is unexpected). In the linked MR, I've elevated the try/catch statements to better catch those exceptions

**Comment by robertstrom** [comment]
I let the Sharphound run to completion and it did generate what looks like a complete result set and zip it up. I was able to ingest the zip file into Bloodhound CE. It looks good. Have performed some basic queries.

2024-10-21T09:13:26.5255950-07:00|INFORMATION|Consumers finished, closing output channel
2024-10-21T09:13:26.6416356-07:00|INFORMATION|Output channel closed, waiting for output task to complete
Closing writers
2024-10-21T09:13:27.3127335-07:00|INFORMATION|Status: 234260 objects finished (+639 89.34401)/s -- Using 238 MB RAM
2024-10-21T09:13:27.3127335-07:00|INFORMATION|Enumeration finished in 00:43:42.1581925
2024-10-21T09:14:22.2050452-07:00|INFORMATION|Saving cache with stats: 18046 ID to type mappings.
 126 name to SID mappings.
 3246 machine sid mappings.
 9 sid to domain mappings.
 0 global catalog mappings.
2024-10-21T09:14:22.3891971-07:00|INFORMATION|SharpHound Enumeration Completed at 9:14 AM on 10/21/2024! Happy Graphing!
COMMANDO 10/21/2024 9:14:22 AM

**Comment by rvazarkar** [comment]
The newest build has the updated commonlib version with the linked MR. Give it a whirl

**Comment by 1upbyte** [comment]
On version 2.5.9 I still receive the same error as OP. I have also verified that `net view \\domain.tld` works.

```
c:\htb\output>Sharphound --domain domain.tld --ldapusername <user> --ldappassword <pass>
2025-01-07T15:39:58.8763217-05:00|INFORMATION|This version of SharpHound is compatible with the 5.0.0 Release of BloodHound
2025-01-07T15:39:58.9861028-05:00|INFORMATION|Resolved Collection Methods: Group, LocalAdmin, Session, Trusts, ACL, Container, RDP, ObjectProps, DCOM, SPNTargets, PSRemote, CertServices
2025-01-07T15:39:59.0014621-05:00|INFORMATION|Initializing SharpHound at 3:39 PM on 1/7/2025
2025-01-07T15:41:20.3146214-05:00|ERROR|Unable to resolve a domain to use, manually specify one or check spelling
```

**Comment by Daniel-CS-Team** [comment]
We encountered the same issue on SharpHound 2.6.1.  PingCastel using the very same machine and user works fine. FIY the Domain Function Level of the target domain is Windows Server 2016. LDAP and SMB Ports are reachable, and I can resolve the domain via nslookup. So it does not seem to be a network issue.
Hopefully the logs here help to identify and fix the issue.

```
PS > RunAsNetonly $UserName $Password $UserDomain "C:\Program Files\SharpHound\SharpHound.exe -c DCOnly -d $Domain --domaincontroller $Domain --zipfilename $Domain -v 0"
starting process
2025-03-19T08:18:38.6540049+00:00|INFORMATION|This version of SharpHound is compatible with the 5.0.0 Release of BloodHound
2025-03-19T08:18:38.8738869+00:00|INFORMATION|Resolved Collection Methods: Group, GPOLocalGroup, Trusts, ACL, Container, ObjectProps, CertServices, LdapServices, SmbInfo
2025-03-19T08:18:38.9211195+00:00|TRACE|Entering initialize link
2025-03-19T08:18:38.9211195+00:00|INFORMATION|Initializing SharpHound at 8:18 AM on 3/19/2025
2025-03-19T08:18:38.9211195+00:00|TRACE|Exiting initialize link
2025-03-19T08:18:38.9297028+00:00|TRACE|Entering TestConnection link, testing domain redacted.tld
2025-03-19T08:18:54.0135952+00:00|DEBUG|[CommonLib ConnectionPoolManager]Resolved identifier redacted.tld to S-1-5-21-redacted-redacted-redacted
2025-03-19T08:18:54.0297571+00:00|DEBUG|[CommonLib LdapConnectionPool]Creating connection for identifier redacted.tld
2025-03-19T08:19:09.0368580+00:00|DEBUG|[CommonLib LdapConnectionPool]Creating connection for identifier redacted.tld
2025-03-19T08:19:24.0642279+00:00|TRACE|Exiting TestConnection link
2025-03-19T08:19:24.0642279+00:00|TRACE|Entering SetSessionUserName
2025-03-19T08:19:24.0642279+00:00|TRACE|Exiting SetSessionUserName
2025-03-19T08:19:24.0846931+00:00|TRACE|Entering InitCommonLib
2025-03-19T08:19:24.0846931+00:00|TRACE|Getting cache path
2025-03-19T08:19:24.0846931+00:00|TRACE|Cache Path: .\MjIyNGM1ZDEtMjU2OS00ZmNmLWEzNjMtMzRmZGYyMmVhN2M5.bin
2025-03-19T08:19:24.0846931+00:00|TRACE|Cache file does not exist
2025-03-19T08:19:24.0846931+00:00|TRACE|Exiting InitCommonLib
2025-03-19T08:19:24.1592236+00:00|TRACE|Entering GetDomainsForEnumeration
d.
   at System.DirectoryServices.ActiveDirectory.Domain.GetDomain(DirectoryContext context)
   at SharpHoundCommonLib.LdapUtils.GetDomain(String domainName, Domain& domain)
2025-03-19T08:19:54.2006508+00:00|DEBUG|[CommonLib LDAPUtils]GetDomain call failed for domain name redacted.tld
System.DirectoryServices.ActiveDirectory.ActiveDirectoryObjectNotFoundException: The specified domain does not exist or cannot be contacteend
```
I tested with SharpHound 2.3.3 and it works fine.

**Comment by RichHacks** [comment]
Same error for me with all the most recent versions. As noted above, 2.4.1 works but also spits a lot of errors into console - unable to resolve forest, and failed to setup LDAP query filter.

**Comment by RichHacks** [comment]
Same on latest RC too. Pingcastle/PurpleKnight all work with a runas netonly session. Bloodhound keeps saying it cant resolve the domain.

**Comment by Daniel-CS-Team** [comment]
I just tested 2.7.1 and am still running in the same problem.

**Comment by gitonglue** [comment]
You can just comment out the two lines in `SharpLink.cs` and recompile. It will then work.

<img width="962" height="218" alt="Image" src="https://github.com/user-attachments/assets/7a2097ad-2abb-45b7-b313-c656da23def5" />

**Comment by l0ss** [comment]
I've got a dollar says it's the use of GetDomain that is causing the issue here. I had to jump through a bunch of stupid hoops to avoid using .net GetDomain and GetForest in Group3r and Snaffler because they weren't working right when used with runas /netonly and proxies and whatnot. 

It's been a while but I'm pretty sure it was because under the hood those methods were using that weird UDP-based "LDAP Ping" protocol? (https://learn.microsoft.com/en-us/openspecs/windows_protocols/ms-adts/895a7744-aff3-4f64-bcfa-f8c05915d2e9)

**Comment by rvazarkar** [comment]
GetDomain is the actual bane of my existence. I hate it so much. I'm going to have to rip all of it out at some point, but its a question of when and how much effort it'll take to fix it. I'll see if theres a short term fix we can implement, but no promises on a timeline right now as its a relatively isolated issue.

**Comment by derekkddj** [comment]
is there any update? i can not get sharphound to work from a computer outside the domain but connected with a VPN.

**Comment by ciyi** [comment]
I sent a pull request to fix this https://github.com/SpecterOps/SharpHound/pull/216
