### ISSUE TITLE
Error in Consumer - DCOnly 

### ISSUE THREAD

**Issue by jstigerwalt** [BloodHoundAD/SharpHound#15]
I am getting an interesting error with the newest version of Sharphound. This does not happen on older versions. 

My Command line is:
`SharpHound.exe -c DCOnly -d corp.stigs.local --memcache`

Here is the error I am getting:

`2022-03-04T19:54:07.5687182-05:00|ERROR|error in consumer
System.NullReferenceException: Object reference not set to an instance of an object.
   at SharpHoundCommonLib.Processors.GPOLocalGroupProcessor.<ProcessGPOXmlFile>d__13.MoveNext()
   at System.Collections.Generic.List1..ctor(IEnumerable1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable1 source)
   at SharpHoundCommonLib.Processors.GPOLocalGroupProcessor.<ReadGPOLocalGroups>d__10.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Sharphound.Runtime.ObjectProcessors.<ProcessOUObject>d__21.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Sharphound.Runtime.ObjectProcessors.<ProcessObject>d__15.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Sharphound.Runtime.LDAPConsumer.<ConsumeSearchResults>d__0.MoveNext()`

Sharphound does finish and this is not a show stopper.

**Comment by rvazarkar** [comment]
Can you try the rolling build and see if it has the same issue?

https://github.com/BloodHoundAD/SharpHound/releases/tag/rolling

**Comment by rvazarkar** [comment]
Should be fixed in v1.0.3
