### ISSUE TITLE
Timeout after 3000 users: LDAP server is unavailable

### ISSUE THREAD

**Issue by Kofl** [BloodHoundAD/SharpHound#17]
Hi,

we run SharpHound and it times out after 3000 sometimes 4000 users. We tried the latest two releases and also the rolling release, same behaviour:

`2022-04-22T10:20:40.8650782+02:00|INFORMATION|Resolved Collection Methods: Group, LocalAdmin, Session, Trusts, ACL, Container, RDP, ObjectProps, DCOM, SPNTargets, PSRemote
2022-04-22T10:20:40.8790787+02:00|INFORMATION|Initializing SharpHound at 10:20 AM on 4/22/2022
2022-04-22T10:20:41.4651864+02:00|INFORMATION|Loaded cache with stats: 2759 ID to type mappings.
 2714 name to SID mappings.
 0 machine sid mappings.
 2 sid to domain mappings.
 0 global catalog mappings.
2022-04-22T10:20:41.4731854+02:00|INFORMATION|Flags: Group, LocalAdmin, Session, Trusts, ACL, Container, RDP, ObjectProps, DCOM, SPNTargets, PSRemote
2022-04-22T10:20:41.8938564+02:00|INFORMATION|Beginning LDAP search for domain.local
2022-04-22T10:21:19.4294650+02:00|INFORMATION|Status: 180 objects finished (+180 4.864865)/s -- Using 195 MB RAM
2022-04-22T10:21:50.6994925+02:00|INFORMATION|Status: 2378 objects finished (+2198 34.97059)/s -- Using 226 MB RAM
2022-04-22T10:22:19.9352352+02:00|WARNING|[CommonLib LDAPUtils]LDAP Exception in Loop: 81. (null). The LDAP server is unavailable.. Filter: (objectsid=\01\05\00\00\00\00\00\05\15\00\00\00\79\11\FE\21\56\64\FC\24\0F\44\89\1D\F3\55\02\00). Domain: domain.local
System.DirectoryServices.Protocols.LdapException: The LDAP server is unavailable.
   at System.DirectoryServices.Protocols.LdapConnection.SendRequest(DirectoryRequest request, TimeSpan requestTimeout)
   at SharpHoundCommonLib.LDAPUtils.<QueryLDAP>d__33.MoveNext() in D:\a\SharpHoundCommon\SharpHoundCommon\src\CommonLib\LDAPUtils.cs:line 833
2022-04-22T10:22:19.9352352+02:00|WARNING|[CommonLib LDAPUtils]LDAP Exception in Loop: 81. (null). The LDAP server is unavailable.. Filter: (samaccountname=INNKDI210D$). Domain: domain.local
System.DirectoryServices.Protocols.LdapException: The LDAP server is unavailable.
   at System.DirectoryServices.Protocols.LdapConnection.ConstructResponse(Int32 messageId, LdapOperation operation, ResultAll resultType, TimeSpan requestTimeOut, Boolean exceptionOnTimeOut)
   at System.DirectoryServices.Protocols.LdapConnection.SendRequest(DirectoryRequest request, TimeSpan requestTimeout)
   at SharpHoundCommonLib.LDAPUtils.<QueryLDAP>d__33.MoveNext() in D:\a\SharpHoundCommon\SharpHoundCommon\src\CommonLib\LDAPUtils.cs:line 833
2022-04-22T10:22:19.9352352+02:00|WARNING|[CommonLib LDAPUtils]LDAP Exception in Loop: 81. (null). The LDAP server is unavailable.. Filter: (objectsid=\01\05\00\00\00\00\00\05\15\00\00\00\79\11\FE\21\56\64\FC\24\0F\44\89\1D\5A\1B\02\00). Domain: domain.local
System.DirectoryServices.Protocols.LdapException: The LDAP server is unavailable.
   at System.DirectoryServices.Protocols.LdapConnection.ConstructResponse(Int32 messageId, LdapOperation operation, ResultAll resultType, TimeSpan requestTimeOut, Boolean exceptionOnTimeOut)`

Thanks

**Comment by rvazarkar** [comment]
Theres nothing we can do about this exception. As far as we can tell, its just the LDAP server telling us to screw off.

**Comment by Kofl** [comment]
Strangely the python version works fine and is able to fetch all data via ldap

**Comment by yellow-starburst** [comment]
Maybe try throttling .
