### ISSUE TITLE
LDAP connection test failing with "runas /netonly"

### ISSUE THREAD

**Issue by xenoscr** [BloodHoundAD/SharpHound#7]
I have validated with "net view" that I am able to see resources on the target domain.  However, SharpHound.exe is reporting that the LDAP connection test if failing:

<DATE_TIME>|ERROR|LDAP Connection Test Failed. Check if you're in a domain context!

**Comment by ddlees** [comment]
@xenoscr Can you post the exact command you ran w/ all the flags you applied minus any sensitive values? You can replace those values with whatever you want but please have something there so we know you provided a value where a value is expected.

**Comment by xenoscr** [comment]
@ddlees, the options don't seem to matter but what I'm doing is first opening a cmd.exe with runas:

runas /netonly /user:<user>@<domain> cmd

Then from that window, verified that "net view \\<domain>\ ran successfully. 

Then run SharpHound:

SharpHound.exe --CollectionMethods DCOnly,SPNTargets --Domain <domain>

I've even tried adding --DomainController. The LDAP connection check, if I'm reading it right, doesn't specify a domain option. I tried to change it so that it would, that didn't seem to help.

This method worked before. I have multiple domains to collect from that would require me to have multiple systems to collect from without being able to use this method.

**Comment by xenoscr** [comment]
Scratch that... edited the wrong file. Changing:

var result =
                context.LDAPUtils.QueryLDAP("(objectclass=domain)", SearchScope.Subtree, new[] { "objectsid" })
                    .DefaultIfEmpty(null).FirstOrDefault();

to:

var result =
                context.LDAPUtils.QueryLDAP("(objectclass=domain)", SearchScope.Subtree, new[] { "objectsid" }, context.DomainName)
                    .DefaultIfEmpty(null).FirstOrDefault();

Resolved the problem. I think, maybe, that without the domain you're trying to check the domain of the current session and not the target domain. Which could be problematic for a system that's not domain joined or has no trust? Specifying the domain seems to have helped.

**Comment by xenoscr** [comment]
It does add this wrinkle:

2022-02-10T15:49:44.0972328-05:00|ERROR|[CommonLib ACLProc]BuildGUIDCache - Unable to resolve forest
2022-02-10T15:49:44.4061141-05:00|ERROR|[CommonLib ACLProc]BuildGUIDCache - Unable to resolve forest
2022-02-10T15:49:44.6428117-05:00|ERROR|[CommonLib ACLProc]BuildGUIDCache - Unable to resolve forest

**Comment by xenoscr** [comment]
And ended with:

`
2022-02-10T15:55:09.4953514-05:00|INFORMATION|Consumers finished, closing output channel
2022-02-10T15:55:12.6865414-05:00|WARNING|[CommonLib LDAPUtils]Error getting forest, ENTDC sid is likely incorrect

Unhandled Exception: System.ArgumentNullException: Value cannot be null.
Parameter name: key
   at System.Collections.Concurrent.ConcurrentDictionary`2.TryGetValue(TKey key, TValue& value)
   at SharpHoundCommonLib.Cache.GetDomainSidMapping(String key, String& value)
   at SharpHoundCommonLib.LDAPUtils.GetSidFromDomainName(String domainName)
   at SharpHoundCommonLib.LDAPUtils.GetBaseEnterpriseDC()
   at SharpHoundCommonLib.LDAPUtils.<GetWellKnownPrincipalOutput>d__19.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Threading.Tasks.Sources.ManualResetValueTaskSourceCore`1.GetResult(Int16 token)
   at SharpHoundCommonLib.LDAPUtils.<GetWellKnownPrincipalOutput>d__19.System.Threading.Tasks.Sources.IValueTaskSource<System.Boolean>.GetResult(Int16 token)
   at System.Threading.Tasks.ValueTask`1.get_Result()
   at System.Runtime.CompilerServices.ValueTaskAwaiter`1.GetResult()
   at Sharphound.Runtime.CollectionTask.<StartCollection>d__10.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Sharphound.Runtime.CollectionTask.<StartCollection>d__10.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at Sharphound.SharpLinks.<AwaitBaseRunCompletion>d__6.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Sharphound.Program.<>c__DisplayClass0_0.<<Main>b__1>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at CommandLine.ParserResultExtensions.<WithParsedAsync>d__20`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Sharphound.Program.<Main>d__0.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at Sharphound.Program.<Main>(String[] args)
`

Glancing over things, it seems like most issues stem from the domain name not being explicitly specified.

**Comment by rvazarkar** [comment]
Working on this now

**Comment by rvazarkar** [comment]
This should be fixed
